---

- name: Verify that required parameters are set
  ansible.builtin.assert:
    that:
      - selinux is defined
      - ansible_facts['os_family'] == "RedHat"

- name: Disable selinux via config file
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disable"
    owner: root
    group: root
    mode: '0644'
  when: selinux is false
  notify: Disable selinux via kernel args
