---

- name: Verify that required parameters are set
  ansible.builtin.assert:
    that:
      - systemd_services_disabled is defined

- name: Disable systemd services
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: stopped
    enabled: false
  loop_control:
    loop_var: service
  loop: "{{ systemd_services_disabled | list }}"
