---

- name: Verify that required parameters are set
  ansible.builtin.assert:
    that:
      - user is defined

- name: Install vifm package
  ansible.builtin.package:
    state: present
    name:
      - vifm

- name: Clone vifm config repo
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "http://server:3003/GiteaUser/vifm.git"
    dest: "/home/{{ user }}/.config/vifm"
    clone: true
    force: true
    version: master
