---
- name: Restart systemd resolved service
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: restarted
    enabled: true

- name: Create resolve.conf symlink
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    owner: root
    group: root
    force: true
