---

- name: Verify that required parameters are set
  ansible.builtin.assert:
    that:
      - user is defined

- name: Install moneyctl package
  ansible.builtin.package:
    state: present
    name:
      - moneyctl
