---

- name: Verify that required parameters are set
  ansible.builtin.assert:
    that:
      - flatpak_packages_install is defined

- name: Install flatpak package
  ansible.builtin.package:
    state: present
    name: flatpak

- name: Add the FlatHub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak apps
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
    method: system
  loop: "{{ flatpak_packages_install | list }}"

- name: Copy flatpak autoupdate systemd files
  ansible.builtin.copy:
    src: "flatpak-update.{{ extension }}"
    dest: "/etc/systemd/system/flatpak-update.{{ extension }}"
    owner: root
    group: root
    mode: "0644"
  loop_control:
    loop_var: extension
  loop:
    - service
    - timer

- name: Enable flatpak autoupdate systemd timer
  ansible.builtin.systemd:
    name: flatpak-update.timer
    state: started
    enabled: true
    daemon_reload: true
