---

- name: Verify that required parameters are set
  ansible.builtin.assert:
    that:
      - user is defined

- name: Install xonsh package
  ansible.builtin.package:
    state: present
    name:
      - xonsh

- name: Clone xonsh config repo
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "http://server:3003/GiteaUser/xonsh.git"
    dest: "/home/{{ user }}/.config/xonsh"
    clone: true
    force: true
    version: master
