---

- name: Verify that required parameters are set
  ansible.builtin.assert:
    that:
      - user is defined
      - user_home is defined
      - user_age_pubkey is defined

- name: Install age package
  ansible.builtin.package:
    state: present
    name:
      - age

- name: Create age config directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - "{{ user_home }}/.config"
    - "{{ user_home }}/.config/age"

- name: Create age pubkey file
  ansible.builtin.template:
    src: age.pub.j2
    dest: "{{ user_home }}/.config/age/age.pub"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0600"
