---

- name: Verify that required parameters are set
  ansible.builtin.assert:
    that:
      - user is defined
      - user_home is defined

- name: Install bat package
  ansible.builtin.package:
    state: present
    name:
      - bat

- name: Clone bat config repo
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "http://server:3003/GiteaUser/bat.git"
    dest: "{{ user_home }}/.config/bat"
    clone: true
    force: true
    version: master
  notify: Update Bat Cache
