---

- name: Verify that required parameters are set
  ansible.builtin.assert:
    that:
      - user is defined
      - user_home is defined
      - zellij_version is defined
      - zellij_archive_url is defined
      - zellij_binary_file is defined
      
- name: Download zellij binary
  become_user: '{{ user }}'
  ansible.builtin.shell:
    cmd: "wget {{ zellij_archive_url }} -O - | tar -xzf -"
    chdir: "{{ zellij_binary_file | dirname }}"
    creates: "{{ zellij_binary_file }}"

- name: Set zellij binary executable
  ansible.builtin.file:
    path: "{{ zellij_binary_file }}"
    state: file
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  
- name: Clone zellij config repo
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "http://server:3003/GiteaUser/zellij.git"
    dest: "{{ user_home }}/.config/zellij"
    clone: true
    force: true
    version: master
